version: "3.9"
services:
  openhands:
    image: allhandsai/openhands:latest
    container_name: openhands
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/London
    volumes:
      - ../..:/workspace:cached
    restart: unless-stopped


